spring:
  application:
    name: impulse    # 项目名称尽量用小写
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null

server:
  port: 8080

bugumongo:
  db:
    host: 192.168.228.133
    port: 27017
    database: huanyu

logging:
  level:
    root: INFO
  file: impulse.log


